package fhj.shelf.ui;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Map;
import java.util.StringTokenizer;
import java.util.TreeMap;
import java.util.Map.Entry;
import java.util.concurrent.ExecutionException;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

import fhj.shelf.factorys.CommandFactory;
import fhj.shelf.factorys.CommandGetFactoryWithParameters;


/**
 * 
 * Class whose instance gives a User Interface Representation of the domain
 * Class {@code GetOneShelf()}
 *
 * @author Filipa Estiveira, Hugo Leal, José Oliveira
 */
@SuppressWarnings("serial")
public class SearchShelf extends JFrame {

	private static final int BTNDELBOUNDS_HEIGHT = 23;
	private static final int BTNDELBOUNDS_WIDTH = 73;
	private static final int BTNDELBOUNDS_Y = 142;
	private static final int BTNDELBOUNDS_X = 178;
	private static final int JBSBOUNDS_HEIGHT = 23;
	private static final int JBSBOUNDS_WIDTH = 73;
	private static final int JBSBOUNDS_Y = 142;
	private static final int JBSBOUNDS_X = 84;
	private static final int JTFNBOUNDS_HEIGHT = 20;
	private static final int JTFNBOUNDS_WIDTH = 166;
	private static final int JTFNBOUNDS_Y = 23;
	private static final int JTFNBOUNDS_X = 84;
	private static final int JTFFBOUNDS_HEIGHT = 20;
	private static final int JTFFBOUNDS_WIDTH = 166;
	private static final int JTFFBOUNDS_Y = 85;
	private static final int JTFFBOUNDS_X = 84;
	private static final int JTFPBOUNDS_HEIGHT = 20;
	private static final int JTFPBOUNDS_WIDTH = 166;
	private static final int JTFPBOUNDS_Y = 54;
	private static final int JTFPBOUNDS_X = 84;
	private static final int JLVD_HEIGHT = 10;
	private static final int JLVD_WIDTH = 325;
	private static final int JLVBOUNDS_HEIGHT = 10;
	private static final int JLVBOUNDS_WIDTH = 325;
	private static final int JLVBOUNDS_Y = 105;
	private static final int JLVBOUNDS_X = 5;
	private static final int JLFD_HEIGHT = 20;
	private static final int JLFD_WIDTH = 65;
	private static final int JLFBOUNDS_HEIGHT = 20;
	private static final int JLFBOUNDS_WIDTH = 65;
	private static final int JLFBOUNDS_Y = 85;
	private static final int JLFBOUNDS_X = 14;
	private static final int JLCD_HEIGHT = 20;
	private static final int JLCD_WIDTH = 65;
	private static final int JLCBOUNDS_HEIGHT = 20;
	private static final int JLCBOUNDS_WIDTH = 65;
	private static final int JLCBOUNDS_Y = 54;
	private static final int JLCBOUNDS_X = 14;
	private static final int JLSIDD_HEIGHT = 20;
	private static final int JLSIDD_WIDTH = 65;
	private static final int JLSIDBOUNDS_HEIGHT = 20;
	private static final int JLSIDBOUNDS_WIDTH = 65;
	private static final int JLSIDBOUNDS_Y = 23;
	private static final int JLSIDBOUNDS_X = 14;
	private static final int LOCATION_Y = 100;
	private static final int LOCATION_X = 100;
	private static final int SIZE_HEIGHT = 234;
	private static final int SIZE_WIDTH = 350;
	private static final int JTFF_COLUMNS = 20;
	private static final int JTFP_COLUMNS = 20;
	private static final int JTFNAME_COLUMNS = 20;
	private static JButton jbSearch;
	private JButton btnDelete;
	Map<String, CommandFactory> shelfCommands;
	private JTable jtShelfContents;
	private JScrollPane jspShelfContents;
	private JButton btnShelfdetails;
	private JTextField tfInputId;

	/**
	 * Constructor
	 * 
	 * @param shelfCommands
	 */
	public SearchShelf(Map<String, CommandFactory> shelfCommands) {
		this.shelfCommands = shelfCommands;
		

		btnShelfdetails = new JButton("ShelfListElements");
		btnShelfdetails.setBounds(166, 11, 115, 23);
		
		createContentTable();
		// Sets window properties
		setTitle("Shelfs Details");
		setSize(499, 510);
		setLocation(LOCATION_X, LOCATION_Y);
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		setVisible(true);
		getContentPane().setLayout(null);
		getContentPane().add(btnShelfdetails);
		
		tfInputId = new JTextField();
		tfInputId.setBounds(258, 45, 23, 23);
		getContentPane().add(tfInputId);
		tfInputId.setColumns(10);
		getContentPane().add(jspShelfContents);
		
		JLabel lblChooseShelfid = new JLabel("Choose Shelf_id");
		lblChooseShelfid.setBounds(166, 45, 99, 22);
		getContentPane().add(lblChooseShelfid);

		
		
		

		/*
		 * ActionListener listener registration in the button Search and button
		 * Delete.          When an event is generated by this component, is
		 *          created an instance of the inner class EventShelfSearch()
		 * and EventShelfDelete()
		 */
		btnShelfdetails.addActionListener(new EventShelfSearch());
//		btnDelete.addActionListener(new EventShelfDelete());

	}
	
	private JTable createContentTable() {

		jtShelfContents = new JTable(new DefaultTableModel(
			new Object[][] {
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
			},
			new String[] {
				"eid", "TypeElement", "Title", "IsAvailable"
			}
		));

		jspShelfContents = new JScrollPane(jtShelfContents);
		jspShelfContents.setBounds(10, 69, 469, 427);
		jspShelfContents
				.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
//		jspShelfContents.setPreferredSize(new Dimension(JSPSD_WIDTH, JSPSD_HEIGHT));
		jtShelfContents.setCellSelectionEnabled(true);
		// Prevents the selection of more than one table row simultaneously
		jtShelfContents.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		return jtShelfContents;
	}
	
	/**
	 * Inner Class that implements ActionListener Interface, and invoke
	 * actionPerformed method for Search Button. The action is made in an
	 * Background Thread, by run SwingWorker framework by execute a
	 * EventHandling() object.
	 */
	private class EventShelfSearch implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {

			if (tfInputId.getText().equals("")) {
				JOptionPane.showMessageDialog(null, "You must put Shelf_id !");
				cleanFields();
			} else {
				Map<String, String> params = new TreeMap<String, String>();
				params.put("id", tfInputId.getText());
				
				new EventHandling(params).execute();
			}

		}

	}

	/**
	 * Inner Class call in the actionPerformed method
	 * 
	 * @author Filipa Estiveira, Hugo Leal, José Oliveira
	 */
	private class EventHandling extends SwingWorker<Map<String, String>, Void> {
		Map<String, String> params;
		
		
		public EventHandling(Map<String, String> map) {
			this.params = map;
				}
		
		
		@Override
		protected Map<String, String>  doInBackground() throws Exception {

			CommandGetFactoryWithParameters getShelf = (CommandGetFactoryWithParameters) shelfCommands.get("getShelf");
			return getShelf.newInstance(params).execute();
		}

		@Override
		protected void done() {

			try {
				Map<String, String> map = new TreeMap<String, String>();
				
				int i= 0;
				int j =1;
				for (Entry<String, String> element : ((Map<String, String>) get()).entrySet()) 
				{
			
					// Fill the cells in the empty line. The numbering of the
					// columns starts at 0
					
					jtShelfContents.setValueAt(createMapParametersReaders(map, get().get("Element_id_"+j)).get("eid"), i, 0);
					jtShelfContents.setValueAt(createMapParametersReaders(map, get().get("Element_id_"+j)).get("type"), i, 1);
					jtShelfContents.setValueAt(createMapParametersReaders(map, get().get("Element_id_"+j)).get("title"), i, 2);
					jtShelfContents.setValueAt(createMapParametersReaders(map, get().get("Element_id_"+j)).get("IsAvailable"), i, 3);
		
                    j++;
					i++;
				}
				
				
			

			} catch (HeadlessException e) {
				e.printStackTrace();
			} catch (InterruptedException e) {
				e.printStackTrace();
			} catch (ExecutionException e) {
				e.printStackTrace();
			} catch (NullPointerException e) {
				JOptionPane.showMessageDialog(null, "Shelf doesn´t exist" + e);
				cleanFields();
				e.printStackTrace();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}
	}
	private static Map<String, String> createMapParametersReaders(
			Map<String, String> mapParameters, String resp) throws Exception {
		
		StringTokenizer ValueTokenizer = new StringTokenizer(resp, "&");
		
		while (ValueTokenizer.hasMoreElements()) {
			String v =  ValueTokenizer.nextToken();
			StringTokenizer e = new StringTokenizer(v, "=");
			if ( e.countTokens() != 2 ) {
				throw new Exception("Unexpeced format value");
			}
			String key = e.nextToken();
			String value = e.nextToken();
			
			mapParameters.put(key, value);
			
			
		}
		System.out.println("mapParameters"+mapParameters);
		return mapParameters;
	}
	private class EventShelfDelete implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {

			if (tfInputId.getText().equals("")) {
				JOptionPane.showMessageDialog(null, "You must searchFirst");
				cleanFields();
			} else {
			
				Map<String, String> params = new TreeMap<String, String>();
				params.put("id", tfInputId.getText());
				new EventHandlingDelete(params).execute();
			}

		}

	}

	private class EventHandlingDelete extends SwingWorker<Object, Void> {
		Map<String, String> params;
		
		String path;
		boolean modeStandAlone = false;
		public EventHandlingDelete(Map<String, String> map) {
			this.params = map;
		path = "DELETE /shelfs/"+String.valueOf(params.get("id"))+" loginName=Lima&loginPassword=SLB";
		}
		
		
		@Override
		protected Object doInBackground() throws Exception {
			return modeStandAlone;

	
		}

		@Override
		protected void done() {

			try {
				JOptionPane.showMessageDialog(null,
						"Delete Shelf " + get());
			} catch (HeadlessException | InterruptedException
					| ExecutionException e) {

				e.printStackTrace();
			}
			cleanFields();

		}
	}

	/**
	 * Method to clean all fields in JTextField
	 */
	private void cleanFields() {
		tfInputId.setText("");
		

	}
}
